# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0002_auto_20170120_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='displayComments',
            fields=[
                ('articles_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commentApp.Articles')),
            ],
            bases=('commentApp.articles',),
        ),
    ]
