# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0003_displaycomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaycomments',
            name='articles_ptr',
        ),
        migrations.DeleteModel(
            name='displayComments',
        ),
    ]
